#+TITLE: 一个抗污染，同时CDN友好的DNS代理

*急需各个平台上的静态二进制版本, 有兴趣参与的同学请联系 zhina 横杠 dns at riaqn dot org*

目前已经有的二进制版本:
|        | Linux | MacOS | Windows |
|--------+-------+-------+---------|
| x86_64 | ✓     | ✓     |         |
| x86    |       | n/a   |         |
| ARMv7l | ✓     | n/a   |         |
| ...    |       |       |         |

请到Releases页下载.

之所以要写这个是因为已有的 ChinaDNS-C 经常行为异常,所以不如直接自己写
一个. 用haskell是因为
- 高并发
- 静态安全
- 开发效率高

* 概述
本软件的自带解析策略:
1. 收到一个请求, 同时向国内DNS (例如 =114.114.114.114= )和国外DNS (例
   如 =8.8.8.8=)发出.
2. 先看国内DNS返回的结果(如果国内DNS失败,则直接失败), 如果包含国外IP,
   则到3,否则返回国内结果.
3. 看国外DNS返回的结果,如果国外DNS失败,则失败.

*注意: 对于国外DNS我们只会走TCP.*

如果你对解析策略有任何建议,欢迎到issues页提出. 

* 配置
本软件提供最小化的配置接口, 接受以下环境变量:
- =HOST= 绑定的地址, 默认 =127.0.0.1=
- =PORT= 绑定的端口, 默认 =5300=
- =ZHINA_HOST= 国内的上游服务器地址, 默认 =114.114.114.114=

  请不要用阿里的DNS (223.5.5.5), 因为他们不支持基于 TCP 的查询, 对于部
  分请求会报 Timeout.
- =ZHINA_PORT= 国内的上游服务器端口, 默认 =53=
- =WORLD_HOST= 国外的上游服务器地址, 默认 =8.8.8.8=
- =WORLD_PORT= 国外的上游服务器端口, 默认 =53=
- =ZHINA_UDP_TIMEOUT= 访问国内UDP上游的超时, 单位 μs, 默认 =100000=
- =ZHINA_TCP_TIMEOUT= 访问国内TCP上游的超时, 单位 μs, 默认 =1000000=
- =WORLD_TCP_TIMEOUT= 访问国外TCP上游的超时, 单位 μs, 默认 =5000000=

对于更细力度的自定义,请fork后修改. 如果你觉得你的修改对于别人也会有价
值,欢迎 pull request.
- 如果要修改上游服务器/本地服务器,请查看 [[src/Main.hs]]
- 如果要修改解析策略,请查看 [[src/ZhinaDNS.hs]]

* 运行
本软件在启动时会从 =stdin= 读入中国的 IPv4 列表, 格式大概如下:
#+begin_example
  # this is allowed
    # this is also allowed
     
  #^ empty line (with or without spaces) is allowed
  #v ip range prefixed or suffixed with spaces is allowed
     1.0.1.0/24
  #v single ip    address is also allowed
   127.0.0.1
#+end_example

本项目自带了一个能从 [[ftp://ftp.ripe.net/pub/stats/apnic/][ripe.net]] 的公开数据库生成该文件的脚本
[[china.awk]], *请修改该文件并且加入你的VPS的IP地址*, 然后用以下命令生成中国 IPv4 列表:
#+begin_src sh
curl ftp://ftp.ripe.net/pub/stats/apnic/delegated-apnic-latest | ./china.awk > china.txt
#+end_src sh
此时 =china.txt= 里就是中国的IP了. 现在就可以运行此程序了:
#+begin_src sh
  ZHINA_TCP_TIMEOUT=2000000 ./zhina-dns < china.txt
#+end_src

建议在本服务的外面套一层pdnsd, 参考配置如下:
#+begin_example
  server {
          label= "zhina-dns";
          ip = 127.0.0.1;
          port = 5300;
          edns_query=off;
          timeout=5;     
          purge_cache=off; 
  }
  server {
          label= "upstream";
          file = "/etc/resolv.conf.upstream"; 
          timeout=1;
          caching=off;
  }
#+end_example
这样在 =zhina-dns= 失败后, pdnsd会临时返回 ISP 提供的IP而不做cache.

* 待办
  以下大多数功能其实都是上游库 [[https://github.com/riaqn/resolve][resolve]] (也是我维护的) 需要做的,上游库
  增加了之后,在本软件中添加相应功能就很简单.
  - cache
  - edns支持
  - =resolv.conf= 支持



